model = "gpt-6-luna"
model_reasoning_effort = "high"
approval_policy = "on-request"
personality = "pragmatic"
service_tier = "priority"

notify = [ "C:\\Users\\user\\AppData\\Local\\OpenAI\\Codex\\runtimes\\cua_node\\71e3f41277f96d73\\bin\\node_modules\\@oai\\sky\\bin\\windows\\codex-computer-use.exe", "turn-ended" ]
[windows]
sandbox = "unelevated"

[projects.'c:\users\user\desktop\quizlaa']
trust_level = "trusted"

[projects.'c:\users\user\documents\codex\2026-05-04\ai-add-a-codex-shortcut-at']
trust_level = "trusted"

[projects.'c:\users\user\desktop\codex']
trust_level = "trusted"

[projects.'c:\users\user\desktop\insurance-crm']
trust_level = "trusted"

[projects.'c:\users\user\desktop\ecoworld']
trust_level = "trusted"

[projects.'c:\users\user\documents\codex\2026-05-12\ai-if-i-use-5-3']
trust_level = "trusted"

[projects.'c:\users\user\desktop\ecoworld2']
trust_level = "trusted"

[projects.'c:\users\user\.codex']
trust_level = "trusted"

[projects.'c:\users\user\desktop\angel-interior']
trust_level = "trusted"

[projects.'c:\users\user\desktop\zenius']
trust_level = "trusted"

[projects.'c:\users\user\desktop\trash-container-app']
trust_level = "trusted"

[projects.'c:\users\user\documents\restore-local']
trust_level = "trusted"

[projects.'c:\users\user\documents\supabase-project-backup-restore']
trust_level = "trusted"

[projects.'c:\users\user\desktop\angel-interior\admin-panel-angel']
trust_level = "trusted"

[projects.'c:\users\user\desktop\vipbillion']
trust_level = "trusted"

[projects.'c:\users\user\desktop\quizlaa\admin-panel-quizlaa']
trust_level = "trusted"

[projects.'c:\users\user\desktop\kushiro']
trust_level = "trusted"

[projects.'c:\xampp\htdocs']
trust_level = "trusted"

[projects.'c:\users\user\desktop\vipbillion\admin-vipbillion']
trust_level = "trusted"

[projects.'c:\users\user\desktop\kushiro\webapp-kushirobbq']
trust_level = "trusted"

[projects.'c:\xampp\htdocs_86cara']
trust_level = "trusted"

[projects.'c:\users\user\desktop\test']
trust_level = "trusted"

[projects.'c:\users\user\desktop\sgmy189_special']
trust_level = "trusted"

[projects.'c:\users\user\desktop\kingsguard']
trust_level = "trusted"

[projects.'c:\users\user\desktop\test\admin-panel-website-airbnb']
trust_level = "trusted"

[projects.'c:\users\user\desktop\hnphomestay']
trust_level = "trusted"

[projects.'c:\users\user\desktop\admin-panel-labour-v4']
trust_level = "trusted"

[projects.'c:\users\user\desktop\genieskinbeauty']
trust_level = "trusted"

[projects.'c:\users\user\desktop\test1\skin2\html.themehour.net\rasm\demo']
trust_level = "trusted"

[projects.'d:\project\mincorner']
trust_level = "trusted"

[projects.'d:\backup\zeta-website-v4']
trust_level = "trusted"

[projects.'d:\backup\website-zetasoftware']
trust_level = "trusted"

[projects.'d:\backup\senseidc']
trust_level = "trusted"

[projects.'c:\users\user\desktop\cermin_v2']
trust_level = "trusted"

[projects.'c:\users\user\desktop\mermaid']
trust_level = "trusted"

[projects.'c:\users\user\desktop\saleshero']
trust_level = "trusted"

[projects.'c:\users\user\desktop\thongthai2\admin-panel-thongthai']
trust_level = "trusted"

[projects.'c:\users\user\desktop\motorcycle']
trust_level = "trusted"

[projects.'c:\users\user\desktop\motorcycle\jambolive']
trust_level = "trusted"

[projects.'c:\users\user\desktop\thongthai2\thongthaimassage_v3']
trust_level = "trusted"

[projects.'c:\users\user\desktop\motorcycle\fc-moto-new']
trust_level = "trusted"

[projects.'c:\users\user\desktop\huwa']
trust_level = "trusted"

[projects.'c:\users\user\desktop\edsb']
trust_level = "trusted"

[projects.'d:\project\xhs-tiktok-inbox']
trust_level = "trusted"

[projects.'d:\project\vipbillion']
trust_level = "trusted"

[features]
memories = true
js_repl = false

[marketplaces.openai-bundled]
source_type = "local"
source = '\\?\C:\Users\user\.codex\.tmp\bundled-marketplaces\openai-bundled'

[marketplaces.openai-primary-runtime]
last_updated = "2026-05-13T17:06:39Z"
source_type = "local"
source = '\\?\C:\Users\User\.cache\codex-runtimes\codex-primary-runtime\plugins\openai-primary-runtime'

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."google-drive@openai-curated"]
enabled = true

[plugins."browser-use@openai-bundled"]
enabled = true

[plugins."supabase@openai-curated"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."codex-app-tools@openai-bundled"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."unified-computer-use@openai-bundled"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[mcp_servers.gitnexus]
command = 'C:\Users\user\AppData\Roaming\npm\gitnexus.cmd'
args = ["mcp"]

[mcp_servers.node_repl]
args = []
command = 'C:\Users\user\AppData\Local\OpenAI\Codex\runtimes\cua_node\71e3f41277f96d73\bin\node_repl.exe'
env_vars = ["CODEX_WINDOWS_REGISTERED_CORE"]
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = 'C:\Users\user\AppData\Local\OpenAI\Codex\runtimes\cua_node\71e3f41277f96d73\bin\node_modules'
NODE_REPL_NODE_PATH = 'C:\Users\user\AppData\Local\OpenAI\Codex\runtimes\cua_node\71e3f41277f96d73\bin\node.exe'
NODE_REPL_TRUSTED_CODE_PATHS = 'C:\Users\user\.codex;C:\Users\user\AppData\Local\OpenAI\Codex\runtimes\cua_node\71e3f41277f96d73\bin\node_modules'
CODEX_HOME = 'C:\Users\user\.codex'
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab,mcpapps"
BROWSER_USE_TINYSKY_ENABLED = "1"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = ""
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = ""
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.930.61225"
NODE_REPL_TRUSTED_SERVICES = '{"browser":"C:/Users/user/.codex/plugins/cache/openai-bundled/browser/26.930.61225/scripts/browser-service.mjs","sky":"@oai/sky/service"}'
SKY_CUA_NATIVE_PIPE = "1"
SKY_CUA_NATIVE_PIPE_DIRECTORY = '\\.\pipe\codex-computer-use-4ea873e4-4c11-4833-8e6c-eeff1d34089f'
CODEX_CLI_PATH = 'C:\Users\user\AppData\Local\OpenAI\Codex\bin\5ea220ae823df3d7\codex.exe'
NODE_REPL_UNTRUSTED_ENV_ALLOWLIST = "CODEX_WINDOWS_REGISTERED_CORE"

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[desktop]
ambient-suggestions-enabled = true
appearanceTheme = "dark"
dictationDictionary = []
git-pull-request-merge-method = "merge"
conversationDetailMode = "STEPS_PROSE"
worktree-keep-count = 10
external-agent-import-sync-enabled = false
followUpQueueMode = "steer"

[memories]
disable_on_external_context = true
